name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t europe-west3-docker.pkg.dev/galvanic-cirrus-437510-m8/test-repo/simple-app:${{ github.sha }} .
  
    - name: Push Docker image to GCR
      run: |
        docker push europe-west3-docker.pkg.dev/galvanic-cirrus-437510-m8/test-repo/simple-app:${{ github.sha }}
